### ISSUE TITLE
blur image at higher fps

### ISSUE THREAD

**Issue by Rajeshlaguri** [indrekluuk/LiveOV7670_stm32-arduino#1]
This is the problem that i am facing at 15 fps. Can you please suggest what should I change for this.
The image is coming clearly and then blurry frame ,and is repeating.
I am only getting proper image at 9 fps in first function  and at prescaler value 5 in third function. 

![1](https://user-images.githubusercontent.com/28979822/27683237-e399e682-5ce2-11e7-86c7-e0cfe210631e.png)
![2](https://user-images.githubusercontent.com/28979822/27683238-e39d0178-5ce2-11e7-8b93-363c8a7bf85f.png)
![3](https://user-images.githubusercontent.com/28979822/27683239-e39eff5a-5ce2-11e7-86b4-d5a3b3bef3a4.png)
![4](https://user-images.githubusercontent.com/28979822/27683240-e39f9b2c-5ce2-11e7-9f85-befc1a18da9d.png)

**Comment by indrekluuk** [comment]
The latest code in the repository (only change BufferedCameraOV7670_QQVGA::FPS_12_Hz to BufferedCameraOV7670_QQVGA::FPS_15_Hz) is  stable for me.

Maybe the issue is with the cable lengths. Long cables distort the signal and can act as antennas. Maybe at 15 fps it becomes a problem.

I have soldered everything to a board with very short wires:
![ov7670](https://user-images.githubusercontent.com/1666508/27759377-31fcc7da-5e38-11e7-9e6b-17db2557a8f4.jpg)
![ov7670_2](https://user-images.githubusercontent.com/1666508/27759403-d418bde4-5e38-11e7-8c95-8c74ec428f1a.jpg)

**Comment by Rajeshlaguri** [comment]
Hi , 
I have soldered the pcb with wire length as minimum as possible .But i am able to achieve the similar results . Its working great at 12 fps QQVGA , but with with 15fps there is an issue .
Have you tried this concept with bigger display and better micro-controller.I wish to use 3.5'' or 4.3'' display at 15fps. I wish to take all the learning from you to a better solution. Can you suggest some boards and some documentation about the project with them. 
Thank you.

**Comment by indrekluuk** [comment]
You could try moving the asm volatile("nop"); around a little. Maybe it helps with the 15Hz. It problably is synchronization isssue.

```

  } else if (framesPerSecond == FPS_15_Hz) {


    waitForPixelClockHigh();

    pixelBuffer.writeBufferPadding = 0;
    uint16_t bufferIndex = 0;
    while (bufferIndex < getPixelBufferLength()) {
      waitForPixelClockLow();
      asm volatile("nop");
      pixelBuffer.writeBuffer[bufferIndex++] = readPixelByte();

      waitForPixelClockLow();
      asm volatile("nop");
      pixelBuffer.writeBuffer[bufferIndex++] = readPixelByte();
    }

```

You should get better frame rate and/or resolution with more powerful CPU. Your probably don't need to change the code much if you use more powerful STM32.
